# Generated by Django 5.1.2 on 2024-10-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=128)),
                ('video_content', models.FileField(upload_to='videos/')),
                ('user', models.IntegerField()),
                ('like', models.TextField()),
                ('dislike', models.TextField()),
                ('created_at', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
