# Generated by Django 5.1.2 on 2024-10-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_content',
            field=models.ImageField(upload_to='media'),
        ),
    ]
